# Automatically generated file. DO NOT MODIFY
#
# This file is generated by device/xiaomi/ruby/setup-makefiles.sh

LOCAL_PATH := $(call my-dir)

ifeq ($(TARGET_DEVICE),ruby)

$(call add-radio-file-sha1-checked,radio/audio_dsp.img,798ad182d100686a972acdf21e3d904e3847b56f)
$(call add-radio-file-sha1-checked,radio/cam_vpu1.img,ae7e86059e20debbd92505e717c630a977e68481)
$(call add-radio-file-sha1-checked,radio/cam_vpu2.img,6df2ca52920e7d88a489ef9a4ed9d4e6e5526515)
$(call add-radio-file-sha1-checked,radio/cam_vpu3.img,6a8e7bb8c44e3174b3274a7e2365e3a6a482ea3e)
$(call add-radio-file-sha1-checked,radio/dpm.img,561c9ad64d2b97ffb0b2a2662a51f2e40d9707e0)
$(call add-radio-file-sha1-checked,radio/gz.img,8667d2843b41b23b7711dce8931db4b04c0a6ef2)
$(call add-radio-file-sha1-checked,radio/lk.img,d1d008ed4d536c83ccda794883537c6950bdffc6)
$(call add-radio-file-sha1-checked,radio/logo.img,291aebc581aa2a2f9284dc7b851202323b621dd2)
$(call add-radio-file-sha1-checked,radio/mcupm.img,cdaf1e04b069942a3ff1ac4e5e18590ab3e5b256)
$(call add-radio-file-sha1-checked,radio/md1img.img,bf1e7adb64d69c357610f4f96be9b47fe773ea1a)
$(call add-radio-file-sha1-checked,radio/pi_img.img,9a416f51af4b6aa03a1db856fbcdf3cb3679769b)
$(call add-radio-file-sha1-checked,radio/preloader.img,17fc82b8dbcf5a661e124e2e4259975e44ad63e8)
$(call add-radio-file-sha1-checked,radio/scp.img,8612d9243696c7c1d67aa52af606462c55433f32)
$(call add-radio-file-sha1-checked,radio/spmfw.img,040da18437d4e93e146cfdb83c39b8b0639f64be)
$(call add-radio-file-sha1-checked,radio/sspm.img,85381adbac7aad4f137375b3307f332de8aeb521)
$(call add-radio-file-sha1-checked,radio/tee.img,b1dcd9fec3efa4d6a29b193627af6df3f1d2e772)

endif
